version: '3'
services:
  edge_bird:
    image: ibhde/bird4
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    container_name: bgp_bird
    network_mode: host
    volumes:
      - ./bird.conf:/etc/bird/bird.conf
    restart: always