version: '3'
services:
  es:
    image: elastic/elasticsearch:7.17.10
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=es
      - cluster.name=es-cdn
      - cluster.initial_master_nodes=192.168.5.102
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - transport.publish_host=192.168.5.102
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: elastic/kibana:7.17.10
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  logstash:
    container_name: logstash
    restart: always
    image: elastic/logstash:7.17.10
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044

volumes:
  elastic-data: